name: Maven Build and Deploy  

on:  
  push:  
    branches:  
      - master  # chỉnh sửa theo branch bạn muốn deploy  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Set up JDK 11  
        uses: actions/setup-java@v2  
        with:  
          java-version: '11'  # Bạn có thể thay đổi phiên bản JDK tại đây  

      - name: Cache Maven packages  
        uses: actions/cache@v2  
        with:  
          path: ~/.m2/repository  
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  
          restore-keys: |  
            ${{ runner.os }}-maven-  

      - name: Build with Maven  
        run: mvn clean install  

      - name: Deploy to GitHub Packages  
        env:  
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}  
        run: mvn deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/richard-vu/publish-java-package-with-maven